name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        otp-version: '27.0'
        elixir-version: '1.17.2'

    - name: Run tests
      run: ./test.sh
